/**
 * All dummy content for the portfolio lives here so it is easy to swap out
 * later. The admin panel is the real source of truth once the site is live —
 * this only bootstraps a believable first run.
 */

const img = (seed, w = 1200, h = 900) => `https://picsum.photos/seed/${seed}/${w}/${h}`;
const face = (n) => `https://i.pravatar.cc/240?img=${n}`;

export const profile = {
  name: 'Shubh Singh',
  designation: 'Graphic Designer & Brand Identity Specialist',
  tagline: 'I turn blank canvases into brands people remember.',
  heroWords: ['Brands', 'Posters', 'Packaging', 'Identities', 'Motion'],
  shortBio:
    'Independent graphic designer based in New Delhi, crafting bold identities, packaging and campaign work for founders who refuse to blend in.',
  longBio:
    "I'm Shubh — a graphic designer with 6+ years spent obsessing over type, colour and the tiny details nobody notices but everybody feels.\n\nI started out designing gig posters for local bands, which taught me a lesson I still design by: attention is earned in the first half second. Since then I've built identities for D2C startups, art-directed packaging that sits on shelves across India, and shaped campaigns that actually moved numbers.\n\nMy process is simple — dig until I understand the business, sketch far more than I show, then sharpen one idea until it's undeniable. No mood-board theatre, no design for the sake of an award shelf.",
  avatar: face(12),
  portrait: img('shubh-portrait', 900, 1200),
  heroImages: [img('hero-a', 800, 1000), img('hero-b', 800, 1000), img('hero-c', 800, 1000)],
  email: 'hello@shubhsingh.design',
  phone: '+91 98765 43210',
  location: 'New Delhi, India',
  yearsExperience: 6,
  available: true,
  availabilityText: 'Available for freelance — Jan 2026',
  resumeUrl: '#',
  marqueeWords: [
    'Brand Identity',
    'Packaging',
    'Poster Design',
    'Art Direction',
    'Motion Graphics',
    'Editorial',
    'Typography',
  ],
  stats: [
    { label: 'Projects delivered', value: 120, suffix: '+' },
    { label: 'Happy clients', value: 48, suffix: '+' },
    { label: 'Years designing', value: 6, suffix: '' },
    { label: 'Design awards', value: 9, suffix: '' },
  ],
  socials: [
    { label: 'Behance', url: 'https://behance.net/shubhsingh', icon: 'behance' },
    { label: 'Dribbble', url: 'https://dribbble.com/shubhsingh', icon: 'dribbble' },
    { label: 'Instagram', url: 'https://instagram.com/shubh.designs', icon: 'instagram' },
    { label: 'LinkedIn', url: 'https://linkedin.com/in/shubhsingh', icon: 'linkedin' },
    { label: 'Twitter', url: 'https://twitter.com/shubhdesigns', icon: 'twitter' },
  ],
  tools: ['Photoshop', 'Illustrator', 'InDesign', 'After Effects', 'Figma', 'Blender', 'Procreate'],
};

export const settings = {
  siteTitle: 'Shubh Singh — Graphic Designer',
  logoText: 'Shubh.',
  theme: 'dark',
  accentColor: '#ff5c39',
  accentColor2: '#7c5cff',
  bgColor: '#0a0a0c',
  surfaceColor: '#141419',
  textColor: '#f5f5f7',
  mutedColor: '#9a9aa5',
  fontHeading: "'Syne', sans-serif",
  fontBody: "'Space Grotesk', sans-serif",
  radius: 22,
  showCursor: true,
  showGrain: true,
  showLoader: true,
  showScrollProgress: true,
  showBlobs: true,
  enableContactForm: true,
  maintenanceMode: false,
  maintenanceText: 'Portfolio is getting a fresh coat of paint. Back soon.',
  loaderText: 'Designing something worth your scroll',
  navLinks: [
    { label: 'Home', href: '#home', order: 0 },
    { label: 'About', href: '#about', order: 1 },
    { label: 'Work', href: '#work', order: 2 },
    { label: 'Services', href: '#services', order: 3 },
    { label: 'Contact', href: '#contact', order: 4 },
  ],
  sections: [
    { key: 'hero', label: 'Hero', eyebrow: '', subtitle: '', enabled: true, order: 0 },
    { key: 'marquee', label: 'Marquee', eyebrow: '', subtitle: '', enabled: true, order: 1 },
    {
      key: 'about',
      label: 'About me',
      eyebrow: '01 — Who I am',
      subtitle: 'Designer, problem solver, professional over-thinker of kerning.',
      enabled: true,
      order: 2,
    },
    { key: 'stats', label: 'By the numbers', eyebrow: '', subtitle: '', enabled: true, order: 3 },
    {
      key: 'services',
      label: 'What I do',
      eyebrow: '02 — Services',
      subtitle: 'Full-stack design help, from first sketch to final print file.',
      enabled: true,
      order: 4,
    },
    {
      key: 'work',
      label: 'Selected work',
      eyebrow: '03 — Portfolio',
      subtitle: 'A slice of recent projects. Tap any card for the full case study.',
      enabled: true,
      order: 5,
    },
    {
      key: 'skills',
      label: 'Tools & skills',
      eyebrow: '04 — Toolkit',
      subtitle: 'The software and disciplines I reach for daily.',
      enabled: true,
      order: 6,
    },
    {
      key: 'experience',
      label: 'The journey',
      eyebrow: '05 — Experience',
      subtitle: 'Where I have worked, studied and picked up a few shiny things.',
      enabled: true,
      order: 7,
    },
    {
      key: 'testimonials',
      label: 'Kind words',
      eyebrow: '06 — Testimonials',
      subtitle: 'What clients say once the dust settles.',
      enabled: true,
      order: 8,
    },
    {
      key: 'contact',
      label: 'Get in touch',
      eyebrow: '07 — Contact',
      subtitle: 'Got a project, a rough idea, or just a good brief? Say hello.',
      enabled: true,
      order: 9,
    },
  ],
  ctaHeading: "Let's make something loud.",
  ctaSubtext: 'Currently booking projects for the next quarter. Tell me what you are building.',
  ctaButtonText: 'Start a project',
  footerNote: 'Designed & obsessed over in New Delhi.',
  footerCredit: '© Shubh Singh. All rights reserved.',
  seo: {
    title: 'Shubh Singh — Graphic Designer & Brand Identity Specialist',
    description:
      'Portfolio of Shubh Singh, a New Delhi based graphic designer specialising in brand identity, packaging, poster design and art direction.',
    keywords:
      'graphic designer, brand identity, packaging design, poster design, New Delhi designer, art director',
    ogImage: img('og-cover', 1200, 630),
  },
};

export const projects = [
  {
    title: 'Kettle & Co. — Tea Brand Identity',
    category: 'Branding',
    client: 'Kettle & Co.',
    year: '2025',
    role: 'Brand Identity, Packaging',
    description:
      'A full identity system for a single-origin tea label that wanted to feel modern without losing its roots.',
    longDescription:
      'Kettle & Co. came to me with great tea and a logo made in Word. We rebuilt the brand from the leaf up — a custom wordmark inspired by Devanagari stroke weights, a warm ochre palette, and a modular packaging system that scales across 14 SKUs without a reprint every time a new blend launches.',
    challenge:
      'Shelf presence in a category dominated by heritage brands, with a budget that allowed only two spot colours.',
    solution:
      'A high-contrast wordmark plus a colour-coded band system, so every blend reads as one family from three metres away.',
    outcome: 'Retail sell-through up 38% in the first quarter after relaunch, and stocked in 60 new stores.',
    coverImage: img('kettle-cover'),
    gallery: [img('kettle-1'), img('kettle-2'), img('kettle-3'), img('kettle-4')],
    tools: ['Illustrator', 'Photoshop', 'InDesign'],
    tags: ['Identity', 'Packaging', 'F&B'],
    link: 'https://behance.net/gallery/kettle-and-co',
    linkLabel: 'View on Behance',
    accent: '#e0873a',
    featured: true,
    order: 0,
  },
  {
    title: 'Nightshift — Music Festival Campaign',
    category: 'Poster Design',
    client: 'Nightshift Fest',
    year: '2025',
    role: 'Art Direction, Poster Series',
    description:
      'A 12-poster campaign for an underground electronic festival, built around glitched type and neon halation.',
    longDescription:
      'Nightshift needed a campaign that worked as a six-foot billboard and a 400px Instagram tile. The system pairs a stretched grotesk with scan-line distortion generated in After Effects, then flattened for print. Each artist got a unique colourway pulled from their album art.',
    challenge: 'One visual language across print, social, motion and on-site signage — produced in three weeks.',
    solution:
      'A rule-based poster template with a fixed grid and variable distortion, so the team could ship new artist reveals themselves.',
    outcome: 'Sold out in 9 days. The poster series was picked up by two design publications.',
    coverImage: img('nightshift-cover'),
    gallery: [img('night-1'), img('night-2'), img('night-3')],
    tools: ['Photoshop', 'After Effects', 'Illustrator'],
    tags: ['Campaign', 'Typography', 'Music'],
    link: 'https://behance.net/gallery/nightshift',
    linkLabel: 'View on Behance',
    accent: '#7c5cff',
    featured: true,
    order: 1,
  },
  {
    title: 'Bloom Skincare — Packaging System',
    category: 'Packaging',
    client: 'Bloom',
    year: '2024',
    role: 'Packaging Design, Illustration',
    description:
      'Minimal, botanical packaging for a clean-beauty range that had to survive both e-commerce and shelf.',
    longDescription:
      'Every Bloom product carries a hand-drawn botanical that maps to its hero ingredient. Drawn in Procreate, vectorised, and printed as a soft-touch matte with a single foil hit. The system covers 9 SKUs, refill pouches and the unboxing insert.',
    challenge: 'Looking premium at a mid-market price point, with sustainable substrates that reject most finishes.',
    solution: 'Uncoated stock, one foil accent, and illustration doing the heavy lifting instead of expensive print effects.',
    outcome: 'Reduced packaging cost per unit by 22% while lifting perceived value in customer surveys.',
    coverImage: img('bloom-cover'),
    gallery: [img('bloom-1'), img('bloom-2'), img('bloom-3'), img('bloom-4')],
    tools: ['Illustrator', 'Procreate', 'Photoshop'],
    tags: ['Packaging', 'Illustration', 'Beauty'],
    link: 'https://behance.net/gallery/bloom',
    linkLabel: 'View on Behance',
    accent: '#4fb286',
    featured: true,
    order: 2,
  },
  {
    title: 'Orbit Finance — App Rebrand',
    category: 'Branding',
    client: 'Orbit',
    year: '2024',
    role: 'Identity, UI Direction',
    description: 'Rebranding a fintech app from generic-blue into something with an actual personality.',
    longDescription:
      'Orbit had 200k users and a brand that looked like every other neobank. We built a geometric mark based on orbital paths, a two-tone palette that meets AA contrast everywhere, and a full icon set of 140 glyphs.',
    challenge: 'Rebuilding trust signals while shedding the safe-but-invisible fintech look.',
    solution: 'Kept the structural discipline, injected warmth through a coral accent and a rounded display face.',
    outcome: 'App store conversion improved 17% post-launch.',
    coverImage: img('orbit-cover'),
    gallery: [img('orbit-1'), img('orbit-2'), img('orbit-3')],
    tools: ['Figma', 'Illustrator', 'After Effects'],
    tags: ['Identity', 'Fintech', 'UI'],
    link: 'https://dribbble.com/shots/orbit',
    linkLabel: 'View on Dribbble',
    accent: '#ff5c39',
    featured: false,
    order: 3,
  },
  {
    title: 'The Slow Press — Editorial Design',
    category: 'Editorial',
    client: 'The Slow Press',
    year: '2024',
    role: 'Editorial Design, Typesetting',
    description: 'A 96-page quarterly on independent food culture, typeset entirely in two families.',
    longDescription:
      'A restrained grid, generous margins and a serif/grotesk pairing that lets photography breathe. Built a master InDesign template so the in-house team could lay out future issues without me.',
    challenge: 'A rotating cast of contributors with wildly inconsistent photography quality.',
    solution: 'Three fixed layout archetypes that flatter weak images and celebrate strong ones.',
    outcome: 'Production time per issue dropped from six weeks to two.',
    coverImage: img('press-cover'),
    gallery: [img('press-1'), img('press-2'), img('press-3')],
    tools: ['InDesign', 'Photoshop'],
    tags: ['Editorial', 'Print', 'Typography'],
    link: 'https://behance.net/gallery/slow-press',
    linkLabel: 'View on Behance',
    accent: '#c9a227',
    featured: false,
    order: 4,
  },
  {
    title: 'Volt EV — Motion Identity',
    category: 'Motion',
    client: 'Volt Mobility',
    year: '2023',
    role: 'Motion Design, Art Direction',
    description: 'An animated logo system and launch film for an electric scooter brand.',
    longDescription:
      'The mark charges, discharges and transforms into a loading state, a notification badge and an end-card. Delivered as Lottie files plus broadcast-ready renders.',
    challenge: 'One motion language that works at 24px in-app and on a cinema screen.',
    solution: 'Built the animation on a single easing curve and a fixed 400ms beat, scaled proportionally.',
    outcome: 'Launch film hit 2.1M organic views in the first week.',
    coverImage: img('volt-cover'),
    gallery: [img('volt-1'), img('volt-2')],
    tools: ['After Effects', 'Illustrator', 'Blender'],
    tags: ['Motion', 'Identity', 'Automotive'],
    link: 'https://behance.net/gallery/volt',
    linkLabel: 'View on Behance',
    accent: '#39c5ff',
    featured: false,
    order: 5,
  },
  {
    title: 'Chowk — Street Food Brand',
    category: 'Branding',
    client: 'Chowk',
    year: '2023',
    role: 'Identity, Signage, Menu Design',
    description:
      'Loud, unapologetically Indian branding for a street food chain — truck-lettering energy, modern execution.',
    longDescription:
      'Custom hand-lettered logotype drawn from Indian truck art, paired with a clean grotesk for legibility. Extended into signage, menu boards, uniforms and delivery packaging across 8 outlets.',
    challenge: 'Celebrating vernacular design without tipping into pastiche.',
    solution: 'One expressive element (the lettering) and everything else kept deliberately quiet.',
    outcome: 'Footfall up 41% at the flagship outlet after the refit.',
    coverImage: img('chowk-cover'),
    gallery: [img('chowk-1'), img('chowk-2'), img('chowk-3')],
    tools: ['Illustrator', 'Procreate', 'InDesign'],
    tags: ['Identity', 'Signage', 'F&B'],
    link: 'https://behance.net/gallery/chowk',
    linkLabel: 'View on Behance',
    accent: '#ef476f',
    featured: true,
    order: 6,
  },
  {
    title: 'Atlas Sneakers — Social Campaign',
    category: 'Social Media',
    client: 'Atlas',
    year: '2023',
    role: 'Art Direction, Social Design',
    description: 'A 40-asset launch campaign built for the thumb, not the desktop.',
    longDescription:
      'Every asset designed mobile-first at 9:16, with a safe-zone grid for platform UI. Includes reel templates, carousel systems and story stickers the community could remix.',
    challenge: 'Sustaining momentum across a six-week drop calendar without repeating a single layout.',
    solution: 'A kit of 8 modular blocks that recombine into hundreds of unique-looking posts.',
    outcome: 'Engagement rate 3.4x the brand average.',
    coverImage: img('atlas-cover'),
    gallery: [img('atlas-1'), img('atlas-2'), img('atlas-3')],
    tools: ['Photoshop', 'Figma', 'After Effects'],
    tags: ['Social', 'Campaign', 'Fashion'],
    link: 'https://instagram.com/shubh.designs',
    linkLabel: 'View on Instagram',
    accent: '#ffd166',
    featured: false,
    order: 7,
  },
];

export const services = [
  {
    title: 'Brand Identity',
    icon: '◈',
    description:
      'Logo systems, colour, type and the guidelines that keep it all from falling apart six months later.',
    features: ['Logo & wordmark design', 'Colour and type systems', 'Brand guidelines PDF', 'Stationery & templates'],
    price: 'From ₹45,000',
    image: img('svc-brand', 800, 600),
    order: 0,
  },
  {
    title: 'Packaging Design',
    icon: '▣',
    description: 'Shelf-ready packaging with print-perfect dielines, from a single SKU to a full range.',
    features: ['Structural dielines', 'Label & carton artwork', 'Print-ready files', 'Press supervision'],
    price: 'From ₹35,000',
    image: img('svc-pack', 800, 600),
    order: 1,
  },
  {
    title: 'Poster & Print',
    icon: '❖',
    description: 'Posters, flyers, editorial spreads and anything else that deserves ink on good paper.',
    features: ['Poster series', 'Editorial layout', 'Flyers & collateral', 'Paper & finish consulting'],
    price: 'From ₹12,000',
    image: img('svc-print', 800, 600),
    order: 2,
  },
  {
    title: 'Social Media Design',
    icon: '✦',
    description: 'Templates and campaign assets built mobile-first, so they land on the platform they live on.',
    features: ['Campaign art direction', 'Reel & story templates', 'Carousel systems', 'Monthly retainers'],
    price: 'From ₹18,000/mo',
    image: img('svc-social', 800, 600),
    order: 3,
  },
  {
    title: 'Motion Graphics',
    icon: '➤',
    description: 'Logo stings, explainer animation and Lottie files that keep interfaces alive.',
    features: ['Animated logo systems', 'Explainer videos', 'Lottie / JSON export', 'Social motion assets'],
    price: 'From ₹25,000',
    image: img('svc-motion', 800, 600),
    order: 4,
  },
  {
    title: 'Art Direction',
    icon: '◐',
    description: 'Shoot direction, visual strategy and the taste-check your campaign needs before it ships.',
    features: ['Photoshoot direction', 'Visual strategy', 'Team design reviews', 'Launch campaign oversight'],
    price: 'On request',
    image: img('svc-art', 800, 600),
    order: 5,
  },
];

export const skills = [
  { name: 'Adobe Photoshop', level: 95, category: 'Software', order: 0 },
  { name: 'Adobe Illustrator', level: 97, category: 'Software', order: 1 },
  { name: 'Adobe InDesign', level: 88, category: 'Software', order: 2 },
  { name: 'After Effects', level: 82, category: 'Software', order: 3 },
  { name: 'Figma', level: 90, category: 'Software', order: 4 },
  { name: 'Blender', level: 68, category: 'Software', order: 5 },
  { name: 'Brand Identity', level: 96, category: 'Design', order: 6 },
  { name: 'Typography', level: 94, category: 'Design', order: 7 },
  { name: 'Packaging & Print', level: 90, category: 'Design', order: 8 },
  { name: 'Art Direction', level: 87, category: 'Design', order: 9 },
  { name: 'Motion Design', level: 78, category: 'Design', order: 10 },
  { name: 'Illustration', level: 85, category: 'Design', order: 11 },
];

export const experience = [
  {
    role: 'Independent Graphic Designer',
    company: 'Freelance / Studio Shubh',
    type: 'work',
    startDate: '2022',
    endDate: '',
    current: true,
    location: 'New Delhi, India',
    description:
      'Running a one-person studio serving D2C brands, festivals and publishers. 60+ projects shipped across identity, packaging and campaign work.',
    order: 0,
  },
  {
    role: 'Senior Visual Designer',
    company: 'Pixel Foundry',
    type: 'work',
    startDate: '2020',
    endDate: '2022',
    location: 'Gurugram, India',
    description:
      'Led identity and campaign work for retail and F&B clients. Mentored three juniors and rebuilt the studio design system.',
    order: 1,
  },
  {
    role: 'Graphic Designer',
    company: 'Inkline Creative',
    type: 'work',
    startDate: '2019',
    endDate: '2020',
    location: 'New Delhi, India',
    description: 'Print collateral, social campaigns and packaging support across a busy agency roster.',
    order: 2,
  },
  {
    role: 'B.Des — Communication Design',
    company: 'National Institute of Design',
    type: 'education',
    startDate: '2015',
    endDate: '2019',
    location: 'Ahmedabad, India',
    description:
      'Specialised in graphic design and typography. Graduated with distinction; thesis on Indian vernacular lettering.',
    order: 3,
  },
  {
    role: 'Foundation in Fine Arts',
    company: 'College of Art, Delhi',
    type: 'education',
    startDate: '2014',
    endDate: '2015',
    location: 'New Delhi, India',
    description: 'Drawing, colour theory and printmaking fundamentals.',
    order: 4,
  },
  {
    role: 'Gold — Packaging Design',
    company: 'India Design Awards 2025',
    type: 'award',
    startDate: '2025',
    endDate: '2025',
    description: 'Awarded for the Bloom Skincare packaging system.',
    order: 5,
  },
  {
    role: 'Poster of the Year — Shortlist',
    company: 'Kyoorius Design Awards 2024',
    type: 'award',
    startDate: '2024',
    endDate: '2024',
    description: 'The Nightshift Festival poster series, shortlisted from 1,200 entries.',
    order: 6,
  },
];

export const testimonials = [
  {
    name: 'Ananya Mehta',
    role: 'Founder',
    company: 'Kettle & Co.',
    avatar: face(45),
    quote:
      'Shubh understood our brand better than we did after one call. The identity he built is the reason retailers finally take us seriously.',
    rating: 5,
    order: 0,
  },
  {
    name: 'Rahul Verma',
    role: 'Marketing Head',
    company: 'Nightshift Fest',
    avatar: face(33),
    quote:
      'Twelve posters in three weeks, every single one a banger. He gave us a system our team could actually run with after he left.',
    rating: 5,
    order: 1,
  },
  {
    name: 'Priya Nair',
    role: 'Co-founder',
    company: 'Bloom Skincare',
    avatar: face(47),
    quote:
      'He cut our packaging costs and made it look more expensive. I still do not fully understand how. Worth every rupee.',
    rating: 5,
    order: 2,
  },
  {
    name: 'Karan Malhotra',
    role: 'Product Lead',
    company: 'Orbit Finance',
    avatar: face(52),
    quote:
      'A rare designer who asks about business metrics before opening Illustrator. Our conversion numbers went up because of his work.',
    rating: 5,
    order: 3,
  },
  {
    name: 'Sara DSouza',
    role: 'Editor',
    company: 'The Slow Press',
    avatar: face(26),
    quote:
      'The template he built saved us a month of production per issue. Calm, fast, and never precious about feedback.',
    rating: 5,
    order: 4,
  },
];
